import "./globals.css";

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import {Inter, Raleway} from "next/font/google";

const raleWay = Raleway({subsets : [ "vietnamese" ]});

export const metadata = {
  title : "HDSC | WOMEN",
  description : "Generated by create next app",
};

export default function RootLayout({children}) {
  return (<html lang = "en"><body className = {raleWay.className}>
          <Navbar />{children} <
          Footer / > </body>
    </html>);
}
